### GET ALL USERS
GET http://localhost:3000/users

### CREATE USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Daniel",
    "email": "dgbarbosa96@gmail.com",
    "password": "123"
}

### GET USER BY ID
GET http://localhost:3000/users/22

### DELETE USER BY ID
DELETE http://localhost:3000/users/6

### UPDATE USER BY ID
PATCH http://localhost:3000/users/22
Content-Type: application/json

{
    "name": "Danidasdel"
}